CREATE DATABASE IF NOT EXISTS github_uploader CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE github_uploader;

CREATE TABLE IF NOT EXISTS user_config (
    id INT PRIMARY KEY AUTO_INCREMENT,
    config_key VARCHAR(100) UNIQUE NOT NULL,
    config_value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
